config/routes.rb
Rails.application.routes.draw do
 resources :goals do
   resources :todos do
     member do
       get "sort"
     end
   end
 end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :todos, -> { order("done ASC, position ASC").includes(:goal) }, dependent: :destroy

  validates :title, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :goal
  acts_as_list scope: [:goal_id]

 validates :position, numericality: { only_integer: true, allow_nil: true }
 validates :content, presence: true
 validates :done, inclusion: { in: [true, false] }

 after_initialize :set_default, if: :new_record?

 private

 def set_default
   self.done = false if self.done.blank?
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
 before_action :authenticate_user!
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  def index
   @goals = Goal.all
  end


  # GET /goals/new
  def new
   @goal = current_user.goals.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  def create
   @goal = current_user.goals.new(goal_params)
    if @goal.save
     @status = true
    else
     @status = false
    end
  end

  # PATCH/PUT /goals/1
  def update
    if @goal.update(goal_params)
     @status = true
    else
     @status = false
    end
  end

  # DELETE /goals/1
  def destroy
    @goal.destroy
  end

  private

  def set_goal
   @goal = current_user.goals.find_by(id: params[:id])
   redirect_to(goals_url, alert: "ERROR!!") if @goal.blank?
  end

  def goal_params
    params.require(:goal).permit(:title, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
   redirect_to goals_path if user_signed_in?
 end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
#before_actionで,アクション前に実行されるメソッドを定義しています。
#参考:https://qiita.com/ebi_death/items/3912630e32268c9cce46  
 before_action :authenticate_user!
 before_action :set_goal
 before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  # GET /todos/new
  def new
#@goalに紐付いたtodosをnewしています
   @todo = @goal.todos.new
  end

  # GET /todos/1/edit
  def edit
  end

 def sort
 end

  # POST /todos
  def create
   @todo = @goal.todos.new(todo_params)

    if @todo.save
     @status = true
    else
     @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update  
  # todo_paramsはこのクラスのprivate以下で定義しています。  
    if @todo.update(todo_params)
     @status = true
    else
     @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
  end

  private

 def set_goal
   @goal = Goal.all.find_by(id: params[:goal_id])
   redirect_to(goals_url, alert: "ERROR!!") if @goal.blank?
 end

  def set_todo
   @todo = @goal.todos.find_by(id: params[:id])
  end

  def todo_params
    params.require(:todo).permit(:content, :goal_id, :position, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bs4_bgcolor_for(flash_key)
     case flash_key
     when "success"
       "alert-success"
     when "error"
       "alert-danger"
     when "alert"
     "alert-warning"
     when "notice"
       "alert-info"
     else
       flash_key.to_s
     end
 end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/goals/_form.html.erb
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="goalModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: goal, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="goalModal">お願いをする</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if goal.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>
              <ul>
                <% goal.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/_goal.html.erb
<div class="card bg-light d-inline-block text-wrap h-100 mx-1 goal-card"
  data-model_name="<%= Goal.model_name.singular %>"
  data-id="<%= goal.id %>">
  <div class="d-flex flex-column h-100" style="width: 25rem; min-width: 25rem;">
    <div class="font-weight-bold px-4 py-2 goal-header">
      <div class="pr-5">
        <%= goal.title %>
      </div>
      <div class="text-right position-absolute" style="top: 4px; right: 4px">
        <%= link_to(new_goal_todo_path(goal), title: "コメントをする", class: "btn px-0", remote: true) do %><i class="fas fa-plus align-middle"></i>コメントをする<% end %>
        <div class="btn-group">
          <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v align-middle"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-middle">
            <%= link_to "Edit", edit_goal_path(goal), class: "dropdown-item", remote: true %>
            <%= link_to "Delete", goal, method: :delete, class: "dropdown-item text-danger", remote: true, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body px-2 pb-2 pt-0 overflow-auto todo-cards">
      <%= render partial: "todos/todo", collection: goal.todos, as: :todo %>
    </div>
  </div>
</div>

app/views/goals/create.js.erb
// modalを閉じる処理
$("#goalModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();


// Rails @status => true 画面の書き換え : false モーダルを再度表示
// <% if @status %>
$("#goalsIndex").append("<%= j(render @goal) %>");

// <% else %>
$("#modalArea").html("<%= j(render 'goals/form', goal: @goal) %>")
$("#modalArea").find(".modal").modal('show')
// <% end %>

app/views/goals/destroy.js.erb
// modalを閉じる処理
$("#goalModal").modal("hide");
$("body").removeClass("modal-open");
$(".modal-backdrop").remove();

// 画面の書き換え
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').remove();

app/views/goals/edit.js.erb
// モーダル追加
$("#modalArea").html(
  "<%= j(render 'form', goal: @goal) %>"
);

// フォームにフォーカス
//modalAreaのなかから modalを探してきて、
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
  $("#modalArea").find("form input[type=text]")[0].focus();
})

// モーダル表示
$("#modalArea").find(".modal").modal("show");

app/views/goals/index.html.erb
<div class="bg-home ">
<div class="goal-title-area px-3 bg-home moji-color">
  <h1>手伝ってほしいこと</h1>
  <%= link_to new_goal_path, title: "New", class: "btn p-0 text-dark", remote: true do %>
    <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle moji-color">新しく書き込む</span>
  <% end %>
</div>
<div class="pt-3 p-1 text-nowrap goal-index-area" id="goalsIndex">
  <%= render @goals %>
</div>
</div>

app/views/goals/new.js.erb
$("#modalArea").html("<%= j(render 'form', goal: @goal) %>")

// フォームにフォーカス
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
    $("#modalArea").find("form input[type=text]")[0].focus();
})

$("#modalArea").find(".modal").modal('show')

app/views/goals/update.js.erb
// モーダルを閉じる処理
$("#goalModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();


// Rails @status => true 画面の書き換え : false モーダルを再度表示
// <% if @status %>
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').replaceWith("<%= j(render @goal) %>");

// <% else %>
$("#modalArea").html("<%= j(render 'form', goal: @goal) %>")
$("#modalArea").find(".modal").modal('show')
// <% end %>

app/views/home/index.html.erb
<h1 class="display-1 text-white text-center font-weight-bold" style="text-shadow: 0 0 10px rgba(0,0,0,0.5)">お願い掲示板</h1>
<h2 class="text-center" style="color: #ccc">会話をしよう。</h2>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">Keijiban by Ruby on Rails & Bootstrap 4</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to '掲示板', root_path, class: "navbar-brand" %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav ml-auto">
     <%  if user_signed_in?  %>
       <li class="nav-item">
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
       </li>
     <% else %>
       <li class="nav-item">
         <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
       </li>
       <li class="nav-item">
         <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
       </li>
   <% end %>
   </ul>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>掲示板</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render "layouts/header" %>
     <%= render "layouts/flash" %>
     <div id="modalArea"></div>
     <main>
     <div class="container-fruid h-100 p-2 d-flex flex-column">
    <%= yield %>
     </div>
     </main>
     <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>掲示板</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <div class="row">
          <div class="col-11 col-lg-5 jumbotron mx-auto mt-4" style="box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.2)">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>掲示板</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <main class="bg-home d-flex align-items-center w-100 h-100">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, url: [goal, todo], remote: true, html: {name: "todoForm", class: "p-2"} ) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, rows: 4 %>
  </div>
  <div class="actions text-right">
    <%= link_to "閉じる", new_goal_todo_path(goal), class: "btn btn-secondary", remote: true %>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_modal_form.html.erb
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="goalModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: todo, url: [goal, todo], remote: true, class: "") do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="goalModal">あいう</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if todo.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>
              <ul>
                <% todo.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :content %>
            <%= form.text_area :content, rows: 5 %>
          </div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/_todo.html.erb
<div class="card mt-2 todo-card <%=" text-muted bg-light" if todo.done %>"
  data-model_name="<%= Todo.model_name.singular %>"
  data-goal_id="<%= todo.goal.id %>"
  data-id="<%= todo.id %>">
  <div class="card-body pr-1">
    <div class="card-text pr-4">
      <%= todo.done ? tag.del(){simple_format todo.content} : (simple_format todo.content) %>
    </div>
    <div class="btn-group position-absolute" style="top: 10px; right: 4px">
      <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right text-middle">
       
        <div class="dropdown-divider"></div>
        <%= link_to "編集", edit_goal_todo_path(todo.goal, todo), class: "dropdown-item", remote: true %>
        <%= link_to "削除",
            goal_todo_path(todo.goal, todo),
            method: :delete,
            class: "dropdown-item text-danger",
            remote: true, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <div class="card-text">
      <small class="text-muted">
        <%= todo.created_at.strftime('%Y/%m/%d') %>
      </small>
    </div>
  </div>
</div>

app/views/todos/create.js.erb
// Rails @status => true formの内容消去、要素の追加 : false モーダルを再度表示
// <% if @status %>
// formを空にする / formにフォーカスする
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form [name="todo[content]"]').val("")
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form [name="todo[content]"]').eq(0).focus();

// 順序が入れ替わるため、todosを描画しなおす
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find(".todo-cards").html("<%= j(render partial: 'todos/todo', collection: @goal.todos, as: :todo) %>");

// <% else %>
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
// <% end %>

app/views/todos/destroy.js.erb
// 画面の書き換え
$('[data-model_name="todo"]').filter('[data-goal_id="<%= @goal.id %>"][data-id="<%= @todo.id %>"]').remove();

app/views/todos/edit.js.erb
// モーダル追加
$("#modalArea").html(
  "<%= j(render 'modal_form', todo: @todo, goal: @goal) %>"
);

// フォームにフォーカス
$("#modalArea").find(".modal").on('shown.bs.modal', () => {
  $("#modalArea").find('form [name="todo[content]"]').eq(0).focus();
})

// モーダル表示
$("#modalArea").find(".modal").modal("show");

app/views/todos/new.js.erb
// true すでに一度フォームが表示されている場合 : false まだフォームが表示されてない場合
if ($('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form[name="todoForm"]').length) {
    $('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form[name="todoForm"]').eq(0).toggle()
    $('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
} else {
    $('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('.goal-header').after("<%= j(render 'form', goal: @goal, todo: @todo) %>")
    $('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find('form [name="todo[content]"]').eq(0).focus();
}

app/views/todos/update.js.erb
// モーダルを閉じる処理
$("#goalModal").modal("hide");
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();

// Rails @status => true 画面の書き換え : false モーダルを再度表示
// <% if @status %>
$('[data-model_name="goal"]').filter('[data-id="<%= @goal.id %>"]').find(".todo-cards").html("<%= j(render partial: 'todos/todo', collection: @goal.todos, as: :todo) %>");

// <% else %>
$("#modalArea").html("<%= j(render 'modal_form', goal: @goal, todo: @todo) %>")
$("#modalArea").find(".modal").modal('show')
// <% end %>